services:
  go_app:
    build: ./repo/go_app
    container_name: go_app

  java_app:
    build: ./repo/java_app
    container_name: java_app

  js_app:
    build: ./repo/js_app
    container_name: js_app

  python_app:
    build: ./repo/python_app
    container_name: python_app

  rust_app:
    build: ./repo/rust_app
    container_name: rust_app
